name: default

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd signup-form-gui && npm install
      - run: cd signup-form-gui && npm run build --if-present
      - run: cd signup-form-gui && npm test
      - run: cd signup-form-server && npm install
      - run: cd signup-form-server && npm run build --if-present
      - run: cd signup-form-server && npm test
